--# VERIFICAR STATUS DA CONTA
SET PAGES 1000 LINES 169 LONG 10000
COL USUARIO FOR A30
COL STATUS FOR A20
COL LOCK_DATE FOR A12
COL EXPIRY_DATE FOR A15
COL TABLESPACE FOR A20
COL TEMP FOR A15
COL PASSWORD FOR A30
select u.username as usuario ,
u.account_status as status,
u.lock_date,
u.expiry_date,
u.default_tablespace as tablespace,
u.temporary_tablespace as temp
from dba_users u
where u.username='SIMULADO';


--#ALTERAR SENHA DO USUARIO
ALTER USER LOGONE14 IDENTIFIED BY logone14;


--#TIRAR LIMITE DE TEMPO DE SENHA
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;


--# ALTERAR SENHA USUARIO COM CONTAINER
ALTER USER XPTO IDENTIFIED BY 123 CONTAINER=ALL;
