--#MODO ARCHIVELOG


--#MODO QUE O BANCO SE ENCONTRA
SELECT LOG_MODE FROM V$DATABASE;


--#LOCALIZAR DIRETÓRIO ARCHIVES
ARCHIVE LOG LIST;

SHUTDOWN IMMEDIATE;

STARTUP MOUNT;


--#MODO ARCHIVELOG DESATIVADO
ALTER DATABASE NOARCHIVELOG;


--#MODO ARCHIVELOG ATIVADO
ALTER DATABASE ARCHIVELOG;


--# ABRIR O BANCO
ALTER DATABASE OPEN;


--# ALTERAR O ARCHIVE DESTINATION
alter system set LOG_ARCHIVE_DEST_1 = 'LOCATION=/archive/DB04' ;



--# MOSTRAR O FORMATO DOS ARCHIVELOGS
show parameter log_archive_format;


--# ALTERAR O FORMATO DOS ARCHIVELOGS
alter system set LOG_ARCHIVE_FORMAT = 'db04_t%t_s%s_r%r.arc' scope = SPFILE ;


