--# ARQUIVO DE CONFIGURACAO DO TNSNAMES QUE FICA EM
---------------------------------------------------
vi $ORACLE_HOME/network/admin/tnsnames.ora
/oracle/product/11.2/db_p4/network/admin/tnsnames.ora

ORACLE_HOME=/ora01/product/11.2.0.4/db_p4

--------------------------------------------
---- DAQUI PRA BAIXO EH O ARQUIVO EM SI ----
--------------------------------------------

# tnsnames.ora Network Configuration File: /ora01/product/11.2.0.4/db_p4/network/admin/tnsnames.ora
# Generated by Oracle configuration tools.

DB04 =
    (DESCRIPTION =
        (ADDRESS = (PROTOCOL = TCP) (HOST = 192.168.88.172) (PORT = 1521))
        (CONNECT_DATA =
            (SERVER = DEDICATED)
            (SERVICE_NAME = DB04)
        )
    )
