--# PEGAR O DDL DO OBJETO (exemplos de tipos abaixo)
set long 10000
COL DBMS_METADATA_GET_DDL  FOR A169
select dbms_metadata.get_ddl('VIEW', 'CTB$_INCONSISTENCIA_RESERVA_V', 'ERP') as DBMS_METADATA_GET_DDL from dual ;
-- TABLE, VIEW, MATERIALIZED_VIEW, CONSTRAINT, REF_CONSTRAINT, INDEX, TRIGGER
-- DB_LINK, PACKAGE, PACKAGE_BODY, TABLESPACE, USER, SYSTEM_GRANT, ROLE_GRANT, OBJECT_GRANT


--#DDL DO COMANDO
DEFINE V_USUARIO = 'HANDITDSV'
COL CMD  FOR A169  HEA "GET_&V_USUARIO._PWD_HASH"
with a as (select DBMS_METADATA.GET_DDL('USER','&V_USUARIO') as CMD from dual)
select replace(substr(a.CMD, instr(a.CMD, 'C'), instr(a.CMD, 'DEFAULT') -12), 'CREATE', 'ALTER') || ' ;' as CMD from a ;
