--# VER LIMITES DO BANCO, SE FORAM ATINGIDOS
--------------------------------------------
SET LINES 237 PAGES 10000 LONG 100000 FEED 1 ECHO ON TI ON TRIM ON TERM ON SERVEROUT ON TAB OFF VER OFF DESC LINENUM ON
COL RESOURCE_NAME  FOR A40
select * from v$resource_limit ;
